// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parque.Data;

#nullable disable

namespace Parque.Migrations
{
    [DbContext(typeof(ParqueDbContext))]
    [Migration("20260520140137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parque.Models.Atraccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Atracciones");
                });

            modelBuilder.Entity("Parque.Models.Boleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<string>("TipoBoleta")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("Boletas");

                    b.HasDiscriminator<string>("TipoBoleta").HasValue("Boleta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Parque.Models.Ingreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtraccionId")
                        .HasColumnType("integer");

                    b.Property<int>("BoletaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TipoAcceso")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtraccionId");

                    b.HasIndex("BoletaId");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("Parque.Models.BoletaGeneral", b =>
                {
                    b.HasBaseType("Parque.Models.Boleta");

                    b.HasDiscriminator().HasValue("General");
                });

            modelBuilder.Entity("Parque.Models.BoletaVIP", b =>
                {
                    b.HasBaseType("Parque.Models.Boleta");

                    b.HasDiscriminator().HasValue("VIP");
                });

            modelBuilder.Entity("Parque.Models.Ingreso", b =>
                {
                    b.HasOne("Parque.Models.Atraccion", "Atraccion")
                        .WithMany()
                        .HasForeignKey("AtraccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parque.Models.Boleta", "Boleta")
                        .WithMany()
                        .HasForeignKey("BoletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Boleta");
                });
#pragma warning restore 612, 618
        }
    }
}
